# Generated by Django 5.0.6 on 2024-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails/courses/'),
        ),
    ]
