# Generated by Django 5.0.6 on 2024-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='static/uploads/thumbnails/courses/'),
        ),
    ]
